# Generated by Django 2.0.4 on 2018-04-11 22:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockBed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
                ('bed_type', models.CharField(blank=True, choices=[('ICU/CC', 'ICU/CC'), ('EU', 'EU'), ('MED/SURG', 'MED/SURG'), ('OB', 'OB'), ('SICU', 'SICU'), ('Neg-Pres/Iso', 'Neg-Pres/Iso'), ('OR', 'OR'), ('Peds', 'Peds'), ('PICU', 'PICU'), ('NICU', 'NICU'), ('Burn', 'Burn'), ('Mental-Health', 'Mental-Health'), ('Other', 'Other')], default='ICU', max_length=50)),
                ('message', models.TextField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eBedTrack.Hospital')),
            ],
        ),
    ]
