# Generated by Django 2.0.4 on 2018-04-09 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type_count', models.IntegerField(default=0)),
                ('block_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='hospital_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nurse_id',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='bh',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='status',
        ),
        migrations.AddField(
            model_name='bed',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_type',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AddField(
            model_name='hospitalbed',
            name='b_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='eBedTrack.Bed'),
        ),
        migrations.AddField(
            model_name='hospitalbed',
            name='h_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hos', to='eBedTrack.Hospital'),
        ),
    ]
