# Generated by Django 2.0.4 on 2018-04-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0002_blockbed'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockbed',
            name='status',
            field=models.CharField(default='Reserved', max_length=100),
        ),
    ]
