# Generated by Django 2.0.4 on 2018-04-11 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0004_auto_20180409_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockbed',
            name='hospital_id',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, to='eBedTrack.Hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blockbed',
            name='message',
            field=models.TextField(),
        ),
    ]
